### ISSUE TITLE
Step 5. swarm_node.rules.yml: no such file or directory

### ISSUE THREAD

**Issue by San13** [zeelos/zeelos#1]
I tried to run this command in Step 5 and received the following error.
`🥃 zeelos (master) 💍 docker-app deploy monitoring
`
-----------------_ERROR log --------------------------
WARNING: installing over previously failed installation "monitoring"
Error: Installation failed: Action "install" failed: open configs/prometheus/rules/swarm_node.rules.yml: no such file or directory
container exit code: 1

> However the directory exists in the file directory

These are my docker nodes

```
docker@saturn:~$ docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
excijg3jrx0qfxf3o2f5dam2u     rock64              Ready               Active                                  18.09.6
zb0b73n7822482y6gisvyfdlx *   saturn              Ready               Active              Leader              18.09.6
mq0t8bt32fbv88dcu1da2cpg7     tinkerboard         Ready               Active                                  18.09.6
8pksk7k2id3pklby90gj0p907     upboard             Ready               Active                                  18.09.6
```

**Comment by zeelos** [comment]
There were some changes in the 'docker-app'  tool (version v0.8.0)  and how it handles path resolving so _I guess_ that is the cause of the issue you are seeing. Another possible reason is the docker version (tested against v18.06.1-ce). Back then, I was experimenting with those specific versions and known to work. I suggest you start with downgrading to docker-app to [v0.6.0](https://github.com/docker/app/releases/tag/v0.6.0) and if that fails, downgrade docker to v18.06.1-ce too. If both solutions fail, we will see from there.

That said, there is an another branch that I am working on (check ['gcp'](https://github.com/zeelos/zeelos/tree/gcp) branch) which would be compatible with the latest released docker-app tool plus:

 - separate swarm cluster for each cloud / edge
 - more monitoring tools (e.g [kafkahq](https://github.com/tchiotludo/kafkahq), [portainer](https://www.portainer.io/))
 - script to bootstrap swarm cluster on Google Cloud
 - VPN connection from edge to cloud (using [WireGuard](https://www.wireguard.com/))
- latest versions of all dependencies

Currently I am in the process of bootstrapping a blog post describing the architecture with setup details, but you can have an [early look at it](https://github.com/zeelos/zeelos/tree/gcp) if you are feeling adventurous. This should be up in the next couple of days [on medium.](https://medium.com/@cvasilak)

**Comment by San13** [comment]
> That said, there is an another branch that I am working on (check 'gcp' branch) which would be compatible with the latest released docker-app tool plus:
> 
> separate swarm cluster for each cloud / edge
> more monitoring tools (e.g kafkahq, portainer)
> script to bootstrap swarm cluster on Google Cloud
> VPN connection from edge to cloud (using WireGuard)
> latest versions of all dependencies

Looking forward for this awesome updates and thanks for quick response. 
i am gonna start by downgrading docker app and then docker if needed to be.

I am a follower of yours in medium and would loved to read your upcoming new articles on medium.

**Comment by San13** [comment]
Installation specific version of Docker-app and Docker solve the problem. Thanks.
